#!/bin/csh -f
# pdf-combine: concatenate pdf files
#  (based on pdftk)
#
# usage: pdf-combine -o output.pdf input.pdf...

if ($#argv < 3) then 
   echo usage: pdf-combine -o output.pdf input.pdf...
   exit 1
endif
if ("$1" != "-o") then 
   echo usage: pdf-combine -o output.pdf input.pdf...
   exit 1
endif

pdftk $argv[3-]:q cat output $2
