#!/bin/csh -f
# copy the jpeg Comment to the IPTC:Caption-abstract field,
# editing out some cruft in the process.
foreach file ($*)
  if (! -r $file) continue

  exiftool -b -Comment $file:q \
  | tr \\r \\n \
  | sed -e 's/HOST: Mac OS X 10\.[0-9]*\.[0-9]*/ /g' -e 's/AppleMark/ /g' -e 's/DESCRIPTION: *//' \
  > $file:q.comment

  chmod +w $file:q
  echo -n "$file - "
  exiftool -q "-IPTC:Caption-abstract<=$file:q.comment" $file:q
  exiftool -b "-IPTC:Caption-abstract" $file:q
  chmod -wx $file:q

  rm -f $file:q.comment
end
