#!/bin/bash
#
# cp-datetime: copy the date/time tags from one image to others
#
# usage: cp-datetime fromImage.jpg toImageOrMovie.xxx...
#  (fromImage can be any file readable by exiftool, and toImageOrMovie
#   can be any file for which exiftool can write location metadata).

if [[ $#argv < 2 ]]; then
   echo usage: cp-datetime fromImage.jpg toImageOrMovie.xxx...
   exit 1
fi
   
from="$1"
shift

exiftool -ExtractEmbedded -TagsFromFile "$from" \
  -CreateDate \
  -ModifyDate \
  -CreationDate \
  -TrackCreateDate \
  -TrackModifyDate \
  -MediaCreateDate \
  -MediaModifyDate \
  -CreationDate \
  -DateTimeOriginal \
  -OffsetTime \
  -OffsetTimeOriginal \
  -OffsetTimeDigitized \
  -TimeZone \
  -TimeZoneCity \
  -SubSecTime \
  -SubSecTimeOriginal \
  -SubSecTimeDigitized \
  -SubSecDateTimeOriginal \
 "$@"
