#!/bin/bash
# 
# get updates to any of the directories listed in arguments
# supports git, svn, cvs
#

for dir in "$@"
do
    if [ -d "$dir" ]; then
        echo "getting $dir..."
    else
        echo "$dir" skipped - not a directory
        continue
    fi

    (cd "$dir"; 
        if [ -d .svn ]; then svn update; fi
        if [ -d CVS ]; then cvs update; fi
        if [ -d .git ]; then git pull -q || echo "$dir": failed; fi
        if [ -f .gitmodules ]; then
            # recursively update submodules
            git submodule update --init --rebase --recursive;
        fi
    )
    sleep 1  # for some reason, things lock up if I move too fast
done
