#!/bin/csh -f
# 
# fetch updates to any repository found under the current directory
# supports git, svn, cvs
#

echo git; find . -name .git -print | sed 's/.git//' | xargs get
echo svn; find . -name .svn -print | sed 's/.svn//' | xargs get
echo cvs; find . -name  CVS -print | sed 's/CVS//'  | xargs get
