#!/bin/csh -f 
# print a list of files that I've forgotten to commit, or forgotten to add
# usage: git-to-commit [dir]...
# with no argument, it defaults to .

if ($#argv == 0) then
    set dirs=.
else
    set dirs=($argv:q)
endif

foreach dir ($dirs:q)
    # skip any directory that is not under git control
   if (! -d $dir:q/.git) continue

    # delete Ignored files; 
    (cd $dir:q; \
	git status --porcelain \
	|& sed -e '/^I/d' -e "s=^=$dir:q ="\
    )
end

