#!/bin/bash
#
# Move an existing git tag forward to current commit, and push to remote.
#
# Be sure to commit everything (needed) before running this script!
#
# David Kotz, 2020  <kotz@dartmouth.edu>

if [[ $# != 1 ]]; then
   echo usage: $0 tagname
   exit 1
else
   tagname="$1"
fi

git push --delete origin "$tagname" # remove the existing tag from remote
git tag --force "$tagname"          # move the local tag to the new commit
git push origin master              # push commits to GitHub remote
git push origin "$tagname"          # push tag to GitHub remote
