#!/bin/csh -f 
# print a list of files that I've forgotten to commit, or forgotten to add
# usage: svn-to-commit [dir]...
# with no argument, it defaults to .

if ($#argv == 0) then
    set dirs=.
else
    set dirs=($argv:q)
endif

foreach dir ($dirs:q)
    # skip any directory that is not under svn control
    if (! -d $dir:q/.svn) continue

    # delete Ignored files; 
    (cd $dir:q; \
	svn status \
	|& sed -e '/^I/d' -e "s=^=$dir:q ="\
    )
end



