# bash sources this file for (interactive) login shells only.
# https://medium.com/@kingnand.90/what-is-the-difference-between-bash-profile-and-bashrc-d4c902ac7308

# I find bash_login to be a more descriptive name
if [ -r ~/.bash_login ]; then
   source ~/.bash_login
fi

# The following was added by installation of 'uv', which supports
# python installation and configuration. It added this line to three bash
# configuration files.  See https://docs.astral.sh/uv/ and 2026 email
# from Jonathan.Crossett@dartmouth.edu for more information.
. "$HOME/.local/bin/env"
