
./.spamassassin/auto-whitelist
./.spamassassin/bayes_seen
./.spamassassin/bayes_toks
./blog/Travel/Hiking/Pages/Moosilauke2011_files/Media/IMG_0646/IMG_0646.MOV
./blog/Travel/Hiking/Pages/Moosilauke2012_files/Media/IMG_1782/IMG_1782.MOV
./blog/Travel/Hiking/Pages/Moosilauke2012_files/Media/IMG_1785/IMG_1785.MOV
./blog/Travel/Hiking/Pages/Moosilauke2012_files/Media/IMG_1798/IMG_1798.MOV
./blog/Travel/India_2007/Pages/Movies_files/Media/beggar/beggar.mov
./blog/Travel/India_2007/Pages/Movies_files/Media/taxi1/taxi1.mov
./blog/Travel/India_2011/Pages/Bangalore2011_files/Media/IMG_0573/IMG_0573.MOV
./blog/Travel/Media/2008 CIS Christmas Andy - Medium.m4v
./blog/Travel/Media/2008 CIS Christmas John - Medium.m4v
./blog/Travel/Media/2008 CIS Christmas Mara - Medium.m4v
./blog/Travel/Media/2008 CIS Mara play - Medium.m4v
./blog/Travel/Media/2008 IISc walk to apartment - Mobile.m4v
./blog/Travel/Media/2008 IISc walk to schoolbus - Mobile.m4v
./blog/Travel/Media/2008 to Kharagpur - Mobile.m4v
./blog/Travel/Media/Ajanta panorama.mov
./blog/Travel/Media/CIS choir-desktop.m4v
./blog/Travel/Media/IISc morning sounds 1hour.mp4
./blog/Travel/Media/mobile-1.m4v
./blog/Travel/Media/mobile-3.m4v
./courses/88pervasive/www/parc-movies/UbiCompTab.qt
./courses/88wireless/www/Presentations/BARWAN.mpg
./projects/Archive/DAgents-repository/papers/gray_scalability/OLD/figs/NOMADS.eps,v
./projects/Archive/DAgents/papers/gray_scalability/OLD/figs/NOMADS.eps
./projects/Archive/armada-repository/docs/anl2002/figures/figures.sda,v
./projects/Archive/armada-repository/docs/oldfield_restruct-tr/figures/figures.sda,v
./projects/Archive/armada-repository/docs/thesis/experiments.tgz,v
./projects/Archive/armada/docs/thesis/experiments.tgz
./projects/Archive/campus-repository/maps-old/AutoCAD-map/Campus-Map-Jan2007.dxf,v
./projects/Archive/campus-repository/papers/kim_mobility/graph/map_gaussian.eps,v
./projects/Archive/campus-repository/papers/kim_mobility/graph/map_gaussian.pdf,v
./projects/Archive/campus-repository/papers/kim_mobility/graph/map_hotspots.eps,v
./projects/Archive/campus-repository/papers/kim_mobility/graph/map_hotspots.pdf,v
./projects/Archive/campus-repository/papers/kim_wardriving2/graph/newmap.eps,v
./projects/Archive/campus-repository/papers/kotz_campus-tr/plots/5Sessions/thresh0/data1,v
./projects/Archive/campus-repository/papers/kotz_campus-tr/plots/5Sessions/thresh3/data1,v
./projects/Archive/campus-repository/papers/kotz_campus-tr/plots/5Sessions/thresh30/data1,v
./projects/Archive/campus-repository/papers/kotz_campus/plots/5Sessions/thresh0/data1,v
./projects/Archive/campus-repository/talks/Apple-May03.zip,v
./projects/Archive/campus-repository/talks/Campus-25.ppt,v
./projects/Archive/campus-repository/talks/Campus-50-June03.ppt,v
./projects/Archive/campus-repository/talks/Campus-50-March03.ppt,v
./projects/Archive/campus-repository/talks/Campus-50.ppt,v
./projects/Archive/campus-repository/talks/Campus-Unleashed-2003.ppt,v
./projects/Archive/campus-repository/talks/Intel-WiFiDay-2002/Kotz-Intel-Dec02.ppt,v
./projects/Archive/campus-repository/talks/Mobicom-2002/Mobicom.ppt,v
./projects/Archive/campus-repository/tools/parsers/anon/Attic/macmap,v
./projects/Archive/campus-repository/tools/parsers/anon/Attic/newmacmap,v
./projects/Archive/campus-repository/tools/parsers/anon/misc/Attic/macmap,v
./projects/Archive/campus-repository/tools/parsers/anon/misc/Attic/newmacmap,v
./projects/Archive/campus-repository/wirelessDartmouth-Converted.mov,v
./projects/Archive/campus-repository/wirelessDartmouth.mov,v
./projects/Archive/campus/maps-old/AutoCAD-map/Campus-Map-Jan2007.dxf
./projects/Archive/campus/papers/kim_wardriving2/graph/newmap.eps
./projects/Archive/campus/papers/kotz_campus-tr/plots/5Sessions/thresh0/data1
./projects/Archive/campus/papers/kotz_campus-tr/plots/5Sessions/thresh3/data1
./projects/Archive/campus/papers/kotz_campus-tr/plots/5Sessions/thresh30/data1
./projects/Archive/campus/papers/kotz_campus/plots/5Sessions/thresh0/data1
./projects/Archive/campus/talks/Apple-May03.zip
./projects/Archive/campus/talks/Campus-25.ppt
./projects/Archive/campus/talks/Campus-50-June03.ppt
./projects/Archive/campus/talks/Campus-50-March03.ppt
./projects/Archive/campus/talks/Campus-50.ppt
./projects/Archive/campus/talks/Campus-Unleashed-2003.ppt
./projects/Archive/campus/talks/Intel-WiFiDay-2002/Kotz-Intel-Dec02.ppt
./projects/Archive/campus/talks/Mobicom-2002/Mobicom.ppt
./projects/Archive/campus/wirelessDartmouth-Converted.mov
./projects/Archive/campus/wirelessDartmouth.mov
./projects/Archive/crawdad-repository/advisors/Attic/meeting-112805.mp3,v
./projects/Archive/crawdad-repository/biblio/Attic/group-5303.bib,v
./projects/Archive/crawdad-repository/data/wifidog/data/Attic/contacts-filtered-30logins-kiosk.txt,v
./projects/Archive/crawdad-repository/data/wifidog/data/Attic/mar2007.sqlite,v
./projects/Archive/crawdad-repository/newsletter/March-2007/Attic/mar07.pdf,v
./projects/Archive/crawdad-repository/tools/pcap/testing/Attic/testdump.long,v
./projects/Archive/crawdad-repository/tools/pcap/testing/Attic/wtestdump.long,v
./projects/Archive/crawdad-repository/web/Attic/crawdad-biblio.pdf,v
./projects/Archive/crawdad-repository/web/Attic/timeline_data.js,v
./projects/Archive/crawdad-repository/web/timeline_data.js,v
./projects/Archive/dist-svn.tgz
./projects/Archive/kotzgroup-svn.tgz
./projects/Archive/metrosense-svn.tgz
./projects/Archive/satc13-old-svn.tgz
./projects/Archive/sawmill-repository/src/Xfiles/treeview2/Kerf/data/teth,v
./projects/Archive/sawmill-repository/src/Xfiles/treeview2/perllib/lib/perl5/site_perl/5.8.0/i386-linux-thread-multi/auto/Gtk2/Gtk2.so,v
./projects/Archive/sawmill-repository/src/Xfiles/treeview2/test/bulk.sql,v
./projects/Archive/sawmill-repository/src/Xfiles/treeview2/xml-packet-summary.xml,v
./projects/Archive/solar-repository/glc_solar_resd/datasets.tgz,v
./projects/Archive/solar-repository/glc_solar_resd/results.tgz,v
./projects/Archive/solar-repository/papers/li:mbq07/paper.ps,v
./projects/Archive/solar-repository/papers/li_thesis/multiSources.xls,v
./projects/Archive/solar/glc_solar_resd/datasets.tgz
./projects/Archive/solar/glc_solar_resd/results.tgz
./projects/Archive/solar/papers/li:mbq07/paper.ps
./projects/Archive/solar/papers/li_thesis/multiSources.xls
./projects/Archive/tish-svn.tgz
./projects/Archive/tish-wiki/data/media/Aravind-Eye-Institute.key
./projects/Archive/tish-wiki/data/media/aravindeyeinstitute.key
./projects/Archive/web-repository/db/revs/10
./projects/Archive/web-repository/db/revs/1050
./projects/Archive/web-repository/db/revs/107
./projects/Archive/web-repository/db/revs/108
./projects/Archive/web-repository/db/revs/11
./projects/Archive/web-repository/db/revs/122
./projects/Archive/web-repository/db/revs/133
./projects/Archive/web-repository/db/revs/144
./projects/Archive/web-repository/db/revs/154
./projects/Archive/web-repository/db/revs/186
./projects/Archive/web-repository/db/revs/214
./projects/Archive/web-repository/db/revs/226
./projects/Archive/web-repository/db/revs/227
./projects/Archive/web-repository/db/revs/228
./projects/Archive/web-repository/db/revs/253
./projects/Archive/web-repository/db/revs/28
./projects/Archive/web-repository/db/revs/283
./projects/Archive/web-repository/db/revs/3
./projects/Archive/web-repository/db/revs/310
./projects/Archive/web-repository/db/revs/321
./projects/Archive/web-repository/db/revs/325
./projects/Archive/web-repository/db/revs/326
./projects/Archive/web-repository/db/revs/349
./projects/Archive/web-repository/db/revs/367
./projects/Archive/web-repository/db/revs/368
./projects/Archive/web-repository/db/revs/380
./projects/Archive/web-repository/db/revs/390
./projects/Archive/web-repository/db/revs/4
./projects/Archive/web-repository/db/revs/416
./projects/Archive/web-repository/db/revs/417
./projects/Archive/web-repository/db/revs/419
./projects/Archive/web-repository/db/revs/431
./projects/Archive/web-repository/db/revs/436
./projects/Archive/web-repository/db/revs/44
./projects/Archive/web-repository/db/revs/452
./projects/Archive/web-repository/db/revs/456
./projects/Archive/web-repository/db/revs/47
./projects/Archive/web-repository/db/revs/484
./projects/Archive/web-repository/db/revs/518
./projects/Archive/web-repository/db/revs/54
./projects/Archive/web-repository/db/revs/544
./projects/Archive/web-repository/db/revs/553
./projects/Archive/web-repository/db/revs/555
./projects/Archive/web-repository/db/revs/558
./projects/Archive/web-repository/db/revs/562
./projects/Archive/web-repository/db/revs/565
./projects/Archive/web-repository/db/revs/568
./projects/Archive/web-repository/db/revs/581
./projects/Archive/web-repository/db/revs/64
./projects/Archive/web-repository/db/revs/642
./projects/Archive/web-repository/db/revs/663
./projects/Archive/web-repository/db/revs/674
./projects/Archive/web-repository/db/revs/693
./projects/Archive/web-repository/db/revs/779
./projects/Archive/web-repository/db/revs/805
./projects/Archive/web-repository/db/revs/849
./projects/Archive/web-repository/db/revs/887
./projects/Archive/web-repository/db/revs/890
./projects/Archive/web-repository/db/revs/895
./projects/Archive/web-repository/db/revs/91
./projects/Archive/web-repository/db/revs/951
./projects/Archive/web-repository/db/revs/996
./projects/Archive/web-repository/db/transactions/27-1.txn/rev
./projects/Archive/web-repository/db/transactions/309-1.txn/rev
./projects/Archive/web-repository/db/transactions/364-1.txn/rev
./projects/Archive/web-repository/db/transactions/364-2.txn/rev
./projects/Archive/web-repository/db/transactions/364-3.txn/rev
./projects/Archive/web-repository/db/transactions/366-2.txn/rev
./projects/Archive/web-repository/db/transactions/367-1.txn/rev
./projects/Archive/web-repository/db/transactions/367-3.txn/rev
./projects/Archive/web-repository/db/transactions/554-16.txn/rev
./projects/Archive/web-repository/db/transactions/554-23.txn/rev
./projects/Archive/web-repository/db/transactions/557-1.txn/rev
./projects/Archive/web-repository/db/transactions/9-1.txn/rev
./projects/Archive/wlansec-repository/DIST/deployment/Baker-Berry/Attic/DIST-Baker-Berry-photos.pdf,v
./projects/Archive/wlansec-repository/DIST/deployment/Tuck/Attic/DIST-Byrne-photos.pdf,v
./projects/Archive/wlansec-repository/DIST/deployment/Tuck/Attic/DIST-Murdough-photos.pdf,v
./projects/Archive/wlansec-repository/code/analysis/ecm/outputs_plots_report/falsepositives_overlap/overlapping_78.txt,v
./projects/Archive/wlansec-repository/code/u_DIST/x86_64--linux-gnu/lib/Attic/libethereal.so.0.0.1,v
./projects/Archive/wlansec-repository/demo/wireless/sender/images/Attic/0.ps,v
./projects/Archive/wlansec-repository/papers/scalability/fig/Sudikoff-AMs-landscape.psd,v
./projects/Archive/wlansec-repository/papers/scalability/fig/Sudikoff-AMs.psd,v
./projects/Archive/wlansec-repository/talks/Attic/MAP-PI-Feb08.ppt,v
./projects/Archive/wlansec-repository/talks/MAP-India-Apr09.pptx,v
./projects/Archive/wlansec-repository/talks/MAP-India-Jan09.pptx,v
./projects/Archive/wlansec-repository/talks/MAP-India-Oct08.pptx,v
./projects/Archive/wlansec-repository/talks/MAP-Rutgers-Apr08.ppt,v
./projects/Archive/wlansec/code/analysis/ecm/outputs_plots_report/falsepositives_overlap/overlapping_78.txt
./projects/Archive/wlansec/papers/scalability/fig/Sudikoff-AMs-landscape.psd
./projects/Archive/wlansec/papers/scalability/fig/Sudikoff-AMs.psd
./projects/Archive/wlansec/talks/MAP-India-Apr09.pptx
./projects/Archive/wlansec/talks/MAP-India-Jan09.pptx
./projects/Archive/wlansec/talks/MAP-India-Oct08.pptx
./projects/amulet-docs/papers/abandoned/ccs14/SUBMIT.pdf
./projects/amulet-docs/papers/abandoned/ccs14/talisman_submission_may17_2014.pdf
./projects/amulet-docs/papers/published/mobicom19/SUBMIT.pdf
./projects/amulet-docs/papers/published/mobicom19/figs/amulet100.png
./projects/amulet-docs/papers/published/perhealth2017/SUBMIT.pdf
./projects/amulet-docs/papers/published/pope-bsn2018/THE_FINAL_SUBMITTED_BSN_ORIG.pdf
./projects/amulet-docs/papers/published/pope-bsn2018/source_files/BSN_system_pics.pdf
./projects/auracle-docs/papers/published/IMWUT18/REVISED.pdf
./projects/auracle-docs/papers/published/IMWUT18/SUBMIT.pdf
./projects/auracle-docs/proposals/nsf-abr-2018/Auracle-ABR-confidential-MARKUP.pdf
./projects/auracle-docs/proposals/nsf-abr-2018/latex/SUBMITTED.pdf
./projects/crawdad/central/past-users/final-dump.xml
./projects/crawdad/docs/logos/stickers/crawdad_a4_sheet_cmyk.psd
./projects/web/STARFISH/starfish2/run.tar.Z
./projects/web/agents/papers/gray:thesis.pdf
./projects/web/agents/papers/sundaram:thesis.pdf
./projects/web/mHealthIndia2009/mHealth_India_Workshop_2009/Program_files/Ramaraju.pdf
./projects/web/papers/cornelius-thesis.pdf
./projects/web/papers/kotz:pools.slides.mov
./projects/web/papers/pierson-thesis.pdf
./projects/web/papers/postscript-old/ps-from-pdf/kotz:axioms-tr.ps.gz
./projects/web/papers/prasad-thesis.pdf
./projects/web/rock/RockLog.pdf
./research/fillet.tgz
./research/netsani/legacy/tools/anon/misc/macmap
./research/netsani/legacy/tools/anon/misc/newmacmap
./research/netsani/trunk/eval/assoc_log_2010winter_clean
./research/netsani/trunk/eval/assoc_log_2010winter_macmap6_ap_minute
./research/netsani/trunk/eval/assoc_log_2010winter_macmap6_apidmap_minute
./research/netsani/trunk/eval/assoc_log_2010winter_macmap6_floor_hour
./research/netsani/trunk/eval/assoc_log_2010winter_macmap6_floor_minute
./research/netsani/trunk/eval/assoc_log_2010winter_mactrun5_building_hour
./research/netsani/trunk/eval/assoc_log_2010winter_mactrun6_apidmap_minute
./research/netsani/trunk/eval/assoc_log_2010winter_mactrun6_building_minute
./research/netsani/trunk/eval/assoc_log_2010winter_mapmap6_floor_minute
./research/netsani/trunk/eval/assoc_log_2010winter_mapmap6_floor_minute.txt
./research/netsani/trunk/eval/assoc_log_2010winter_san
./research/netsani/trunk/eval/macmap6_ap_minute.txt
./research/netsani/trunk/eval/macmap6_apidmap_minute.txt
./research/netsani/trunk/eval/macmap6_floor_hour.txt
./research/netsani/trunk/eval/mactrun6_apidmap_minute.txt
./research/netsani/trunk/eval/mactrun6_building_minute.txt
./research/pario-ftp.tgz
./research/pario/workload/Acharya/cholesky.outofcore.tar.gz
./research/sandbox/thesis.tar.gz
./research/starfish.tar.gz
./research/theses2001/ammar/thesis_Code.zip
./research/theses2001/arun/jdev.zip
./research/theses2001/ayorkor/thesis/openh323.zip
./research/tish-wiki.tar.gz
