#!/bin/csh -f
#
# Recursively grep for a string in all files
#
# David Kotz 1992
#
# Usage: grepr string fileORdir...

if ($#argv < 2) then 
  echo Usage: grepr string fileORdir...
  exit 1
endif

set string="$1"
shift

find $* \! -type d -exec zgrep "$string" '{}' \;
