#!/bin/sh
# 
# convert to jpg all photos listed as arguments 
#

for heic in "$@"
do
    if [[ "$heic" =~ .*\.HEIC$ ]]; then
        convert "$heic" "${heic%.HEIC}.jpg"
    elif [[ "$heic" =~ .*\.heic$ ]]; then
        convert "$heic" "${heic%.heic}.jpg"
    else
        echo 1>&2 "unknown file type $heic"
    fi
done
