#!/bin/bash
#
# imagecmp - given an image file, compare its image *content*
# with that in the Dropbox backup of that image file.
#

if [ $# -ne 1 ]; then
    echo usage: imagecmp file
    exit 1
fi

new="$1"
old=~/Dropbox/"LightroomBackup/$1"

convert "$new" rgb:new.rgb
convert "$old" rgb:old.rgb

let diffs=0

if ! cmp -s old.rgb new.rgb; then
    echo "CHANGED:"
    echo " $old"
    echo " $new"
    let diffs++
fi

rm -f old.rgb new.rgb

exit $diffs
