#!/usr/bin/env bash
# This script is a wrapper for scripts run by launchd
# from /Users/dfk/Library/LaunchAgents/*.plist

# They need my usual environment
source ~/.bash_environset

# and the cron-like MAILTO
export MAILTO=dfkotz@mac.com

# pause a few seconds, in case we just woke up and network is not ready
sleep 10

exec "$@"
