#!/usr/local/bin/bash
# This script is a wrapper for scripts run by launchd
# from /Users/dfk/Library/LaunchAgents/*.plist

# They need my usual environment
source ~/.bash_environset

# and the cron-like MAILTO
export MAILTO=dfkotz@mac.com

exec "$@"
