#!/bin/bash
# remove "Icon?" and ".DS_Store" files,
# within any of the directories provided on the commandline. 
if [ $# -gt 0 ]; then
    find "$@" -name Icon\?    -print0 | xargs -0 rm -f
    find "$@" -name .DS_Store -print0 | xargs -0 rm -f
fi
